--taxon table
INSERT INTO taxon (
    TAXONOMIC_ORDER,
    CATEGORY,
    TAXON_CONCEPT_ID,
    COMMON_NAME,
    SCIENTIFIC_NAME,
    SUBSPECIES_COMMON_NAME,
    SUBSPECIES_SCIENTIFIC_NAME
)
SELECT DISTINCT ON (COMMON_NAME) *
FROM taxon_temp;

--location table
INSERT INTO location (
    COUNTRY,
    COUNTRY_CODE,
    STATE,
    STATE_CODE,
    COUNTY,
    COUNTY_CODE,
    IBA_CODE,
    BCR_CODE,
    USFWS_CODE,
    ATLAS_BLOCK,
    LOCALITY,
    LOCALITY_ID,
    LOCALITY_TYPE,
    LATITUDE,
    LONGITUDE
)
SELECT DISTINCT ON (LOCALITY_ID) *
FROM location_temp;

--submission table
INSERT INTO submission (
    LOCALITY_ID,
    OBSERVATION_DATE,
    TIME_OBSERVATIONS_STARTED,
    OBSERVER_ID,
    OBSERVER_ORCID_ID,
    SAMPLING_EVENT_IDENTIFIER,
    OBSERVATION_TYPE,
    PROTOCOL_NAME,
    PROTOCOL_CODE,
    PROJECT_NAMES,
    PROJECT_IDENTIFIERS,
    DURATION_MINUTES,
    EFFORT_DISTANCE_KM,
    EFFORT_AREA_HA,
    NUMBER_OBSERVERS,
    ALL_SPECIES_REPORTED,
    GROUP_IDENTIFIER,
    HAS_MEDIA,
    APPROVED,
    REVIEWED,
    REASON
)
SELECT DISTINCT ON (SAMPLING_EVENT_IDENTIFIER) *
FROM submission_temp;

--observation table
INSERT INTO observation (
    GLOBAL_UNIQUE_IDENTIFIER,
    LAST_EDITED_DATE,
    COMMON_NAME,
	EXOTIC_CODE,
    OBSERVATION_COUNT,
    BREEDING_CODE,
    BREEDING_CATEGORY,
    BEHAVIOR_CODE,
    AGE_SEX,
	SAMPLING_EVENT_IDENTIFIER,
    CHECKLIST_COMMENTS,
    SPECIES_COMMENTS
)
SELECT DISTINCT ON (GLOBAL_UNIQUE_IDENTIFIER) *
FROM observation_temp;