--Purpose: Import data from staging table to final table w/ constraints and a SELECT DISTINCT on primary key for normalization
--Table: Submission

INSERT INTO sub (
    LOCALITY_ID,
    OBSERVATION_DATE,
    TIME_OBSERVATIONS_STARTED,
    OBSERVER_ID,
    OBSERVER_ORCID_ID,
    SAMPLING_EVENT_IDENTIFIER,
    OBSERVATION_TYPE,
    PROTOCOL_NAME,
    PROTOCOL_CODE,
    PROJECT_NAMES,
    PROJECT_IDENTIFIERS,
    DURATION_MINUTES,
    EFFORT_DISTANCE_KM,
    EFFORT_AREA_HA,
    NUMBER_OBSERVERS,
    ALL_SPECIES_REPORTED,
    GROUP_IDENTIFIER,
    HAS_MEDIA,
    APPROVED,
    REVIEWED,
    REASON
)
SELECT DISTINCT ON (SAMPLING_EVENT_IDENTIFIER) *
FROM sub_temp;